POST http://localhost:8080/api/v1/user
Content-Type: application/json

{"name":"ross","email":"ross@test","userInfo":{"ages":15}}

###
GET http://localhost:8080/api/v1/user

###
GET http://localhost:8080/api/v1/page

###
GET http://localhost:8080/api/v1/sort

###
GET http://localhost:8080/api/v1/name?email=ross@test

###
GET http://localhost:8080/api/v1/projections-interface

###
POST http://localhost:8080/api/v1/dynamic
Content-Type: application/json

{"email":"ross2@test"}

###
POST http://localhost:8080/api/v1/user-info
Content-Type: application/json

{"ages":15,"user":{"name":"ross","email":"ross@test"}}

###
GET http://localhost:8080/api/v1/user-info

###
GET http://localhost:8080/api/v1/example

###
GET http://localhost:8080/api/v1/version?name=ross22&time=5000

###
GET http://localhost:8080/api/v1/version?name=ross3&time=1000